import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Pak Draw | Pakistan First Digital Lottery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" type="image/png" />
      </Head>
      <body className="bg-gray-100">{children}</body>
    </html>
  );
}
